# This is a basic workflow that is manually triggered

name: run test of by push

on:
  push:
    branches:
      'feature/*'

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run test
        run: npm cypress run

        
            

